# Generated by Django 5.1.2 on 2024-10-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatPack',
            fields=[
                ('beatpack_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('beatmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=100)),
                ('beatpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeBeat.beatpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeBeat.user')),
            ],
        ),
        migrations.AddField(
            model_name='beatpack',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeBeat.music'),
        ),
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_finished', models.DateTimeField()),
                ('beatmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeBeat.beatmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeBeat.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('beatmap', 'user'), name='unique_user_beatmap')],
            },
        ),
    ]
