# Generated by Django 5.1.2 on 2024-11-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypeBeat', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatpack',
            name='music',
        ),
        migrations.RenameField(
            model_name='highscore',
            old_name='score',
            new_name='highest_combo',
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='title',
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='user',
        ),
        migrations.RemoveField(
            model_name='beatpack',
            name='title',
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='beatmap',
            name='beatmap_title',
            field=models.CharField(default='Untitled', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatmap',
            name='mapmaker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_beatmaps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatmap',
            name='no_of_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='no_of_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='total_note_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatpack',
            name='beatpack_picture',
            field=models.ImageField(blank=True, null=True, upload_to='beatpack_pictures/'),
        ),
        migrations.AddField(
            model_name='beatpack',
            name='beatpack_title',
            field=models.CharField(default='Untitled', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatpack',
            name='music_author',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatpack',
            name='no_of_beatmaps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatpack',
            name='no_of_downloads',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highscore',
            name='accuracy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highscore',
            name='beatpack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TypeBeat.beatpack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highscore',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highscore',
            name='great',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highscore',
            name='mapmaker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mapmaker_highscores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highscore',
            name='miss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highscore',
            name='perfect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highscore',
            name='total_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Profile/DefaultProfile.png', null=True, upload_to='Profile/'),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='difficulty',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
